apiVersion: apps/v1
kind: Deployment
metadata:
  name: rmi-qotd
  labels:
    app: rmi-qotd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rmi-qotd
  template:
    metadata:
      labels:
        app: rmi-qotd
    spec:
      containers:
        - name: rmi-qotd
          image: quay.io/cbowland/rmi_qotd_client
          env:
            - name: SERVER_HOST
              value: rmi-server
